// Code generated by Kitex v0.4.4. DO NOT EDIT.

package publishservice

import (
	"context"
	publish "doushengV4/kitex_gen/publish"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FeedPublish(ctx context.Context, req *publish.FeedRequest, callOptions ...callopt.Option) (r *publish.FeedResponse, err error)
	ActionPublish(ctx context.Context, req *publish.ActionRequest, callOptions ...callopt.Option) (r *publish.ActionResp, err error)
	ListPublish(ctx context.Context, req *publish.ListRequest, callOptions ...callopt.Option) (r *publish.ListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPublishServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPublishServiceClient struct {
	*kClient
}

func (p *kPublishServiceClient) FeedPublish(ctx context.Context, req *publish.FeedRequest, callOptions ...callopt.Option) (r *publish.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FeedPublish(ctx, req)
}

func (p *kPublishServiceClient) ActionPublish(ctx context.Context, req *publish.ActionRequest, callOptions ...callopt.Option) (r *publish.ActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionPublish(ctx, req)
}

func (p *kPublishServiceClient) ListPublish(ctx context.Context, req *publish.ListRequest, callOptions ...callopt.Option) (r *publish.ListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPublish(ctx, req)
}
